apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-service-account
  namespace: inference
  annotations:
    # IMPORTANT: set this to the SAME IAM role that has the correct IRSA trust policy for this SA:
    # system:serviceaccount:inference:inference-service-account
    eks.amazonaws.com/role-arn: arn:aws:iam::996099991204:role/ml-argo-workflow-irsa-role
