apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/luzhac/ml-platform
    targetRevision: main
    path: infra/kubernetes/helm/ml
    helm:
      valueFiles:
        - values-dev.yaml
 

  destination:
    server: https://kubernetes.default.svc
    namespace: challenge-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
