apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/luzhac/ml-platform
    targetRevision: main
    path: inference/k8s   

  destination:
    server: https://kubernetes.default.svc
    namespace: inference

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true