 challenge:
  enabled: true
  appName: "challenge"
  image: "996099991204.dkr.ecr.eu-west-2.amazonaws.com/challenge-repo:latest"
  replicaCount: 2
  port: 5000

  env:
    dynamodbTable: "Challenge"
    s3Bucket: "marscompute-s3-challenge"

  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
