apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.challenge.appName }}
  
spec:
  type: LoadBalancer 
  selector:
    app:  {{ .Values.challenge.appName }}
 

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
