apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-account
  namespace: pipeline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::996099991204:role/ml-mlflow-irsa-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflowtaskresults-writer
  namespace: pipeline
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflowtaskresults-writer-binding
  namespace: pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline-service-account
    namespace: pipeline
roleRef:
  kind: Role
  name: argo-workflowtaskresults-writer
  apiGroup: rbac.authorization.k8s.io
