apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-account
  namespace: pipeline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::996099991204:role/ml-argo-workflow-irsa-role
