name: Build & Push ETL processor

on:
  push:
    branches: [ "main" ]
    paths:
      - "etl/processor/**"
      - ".github/workflows/build-process.yml"
  workflow_dispatch:

jobs:
  build-process:
    runs-on: ubuntu-latest


    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # AWS OIDC
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_access_ecr
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ----------------------------
      #  Buildx
      # ----------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ----------------------------
      # Build & Push
      # ----------------------------
      - name: Build & Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: etl-processor
          IMAGE_TAG: latest
        run: |
          docker buildx build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --push \
            ai-platform/etl/processor
