name: CI Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:

  test:
    runs-on: ubuntu-latest
    environment: challenge

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: inference

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      MODEL_ALIAS: ${{ secrets.MODEL_ALIAS }}
      DRIFT_WINDOW_SIZE: ${{ secrets.DRIFT_WINDOW_SIZE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT }}:role/${{ secrets.GIT_HUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings


  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inference

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install flake8 pylint mypy
      - run: flake8 .
        continue-on-error: true
      - run: pylint app || true
        continue-on-error: true
      - run: mypy app
        continue-on-error: true


  security-scan:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t inference:latest inference/

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "inference:latest"
          format: "table"
          exit-code: "0"
          severity: "CRITICAL,HIGH"


  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    environment: challenge

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT }}:role/${{ secrets.GIT_HUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: marscompute-ml
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG inference/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG